# Configuration for media deaths analysis
#
# Details of the execution, not language-dependent
runtime:
  verbose: true
  # Whether you want to rerun the queries or not - rerunning the queries can take ~30 minutes.
  # If false, the script uses the results found in ./data/media_deaths_mentions.csv
  rerun_queries: true
  # Whether you want to run single keyword queries (only 1 mention per article) vs multiple keyword queries (multiple mentions per article)
  run_single_queries: false
  # Whether you want to overwrite existing files or not
  overwrite: true
  # Whether to use final results for all plots. If TRUE this overrides all analysis
  # and uses the saved results in ./data/media_deaths_results.csv
  use_saved_results: false
  api_sleep: 10

data:
  year: 2023
  language: "en"
  # Data loader module to use for fetching mortality data. This should be a string, matching a registered data loader (see data_loaders/)
  data_loader: "cdc"

# Replace below with desired outlets and collections
outlets:
  - full_name: The New York Times
    id: 1
    short_name: nyt
  - full_name: The Washington Post
    id: 2
    short_name: wapo
  - full_name: Fox News
    id: 1092
    short_name: fox

# Replace below with desired collections
collections:
  - full_name: US Collection
    id: 34412234
    short_name: us

# Replace below with desired causes of death and associated queries
causes_death:
